config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "restaurants#index"


  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end

  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

     # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
    end

   
    member do
      get :dashboard # 瀏覽個別餐廳的 Dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end

  

  end

  resources :categories, only: :show

  resources :users, only: [:index, :show, :edit, :update]
  
  resources :followships, only: [:create, :destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :restaurants, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

belongs_to :user
belongs_to :restaurant

end

app/models/followship.rb
class Followship < ApplicationRecord
  belongs_to :user
  belongs_to :following, class_name: "User"

  validates :following_id, uniqueness: { scope: :user_id }
  
end

app/models/like.rb
class Like < ApplicationRecord
belongs_to :user
belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  
  belongs_to :category, optional: true
  
  has_many :comments , dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user


  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

   def is_liked?(user)
    self.liked_users.include?(user)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
   # 「使用者評論很多餐廳」的多對多關聯
  has_many :comments
  has_many :restaurants, through: :comments
 
  # 「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant


  # User可以跟隨很多人，如果User刪掉的話 follow關係也要被刪掉 也可以被很多人跟隨
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  # User 被Follow的關係
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user




  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

def show
  @categories = Category.all
  @category = Category.find(params[:id])
  @restaurants = @category.restaurants.page(params[:page]).per(9)
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end
  

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController

  def create
    @followship = current_user.followships.build(following_id: params[:following_id])

    if @followship.save
      flash[:notice] = "Successfully followed"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = @followship.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end


  def destroy
    @followship = current_user.followships.where(following_id: params[:id]).first
    @followship.destroy
    flash[:alert] = "Followship destroyed"
    redirect_back(fallback_location: root_path)
  end
  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
 
  def index
    @restaurants = Restaurant.page(params[:page]).per(10) 
    @categories = Category.all    
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
    
  end
  
  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

    # POST /restaurants/:id/favorite
  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

  # POST /restaurants/:id/unfavorite
  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
      @restaurant = Restaurant.find(params[:id])
      @restaurant.likes.create!(user: current_user)
      redirect_back(fallback_location: root_path)
  end

  def unlike
      @restaurant = Restaurant.find(params[:id])
      likes= Like.where(restaurant: @restaurant, user: current_user)
      likes.destroy_all
      redirect_back(fallback_location: root_path)
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]


def index
    @users = User.all
end

def show
  @user = User.find(params[:id])
  @commented_restaurants = @user.restaurants.uniq
  @favorited_restaurants = @user.favorited_restaurants
  @followers = @user.followers
  @followings = @user.followings

end

def edit
end

def update
    if @user.id == current_user.id 


      if @user.update(user_params)
        flash[:notice] = "intro was successfully updated"
        redirect_to user_path(@user)
      else
        flash.now[:alert] = "intro was failed to update"
        render :edit
      end
    else
        flash.now[:alert] = "intro was failed to update : run user"
        render :edit  
    end

end


private
  
  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForm0522</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "餐廳評論網", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
      

      <% if current_user %>
        <li> <p class="navbar-text">Hi, <%= current_user.email %> </p></li>
        <li> <%= link_to('個人頁面', user_path(current_user)) %> </li>
          <% if current_user.admin? %>
            <li><%= link_to('管理後台', admin_restaurants_path) %> </li>
          <% end %>
        <li><%= link_to('登出', destroy_user_session_path, method: :delete) %> </li>
        <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
     <% else %>
        <li><%= link_to('註冊', new_user_registration_path) %> </li>
        <li><%= link_to('登入', new_user_session_path) %> </li>
     <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



 <% if flash[:notice] %>
      <div class="container">
        <div class="row">
          <div class="alert alert-info alert-dismissible" role="alert">
            <%= notice %>
             <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> 
          </div>
        </div>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="container">
        <div class="row"> 
          <div class="alert alert-danger alert-dismissible" role="alert">
            <%= alert %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
        </div>
      </div>
    <% end %>



    <%= yield %>
  </body>
</html>

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
  <%= link_to 'Unfavorite', unfavorite_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Favorite', favorite_restaurant_path(restaurant), method: :post, class: "btn btn-primary" %>
<% end %>
  
<% if restaurant.is_liked?(current_user) %>
  <%= link_to 'Like', unlike_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Unlike', like_restaurant_path(restaurant), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_follow.html.erb
<% if user != current_user %>
  <% if current_user.following?(user)%>
    <%= link_to 'Unfollow', followship_path(user), method: :delete ,class: "btn btn-default"%>
  <% else %>
    <%= link_to 'Follow', followships_path(following_id: user), method: :post , class: "btn btn-default"%>
  <% end %>
<% end %>

app/views/shared/_nav_bar.html.erb
 <ul class="nav nav-tabs">
      <li role="presentation"><%= link_to '首頁', restaurants_path %></li>
      <li role="presentation"><%= link_to 'Feeds', feeds_restaurants_path %></li>
      <li role="presentation"><%= link_to '美食達人', users_path %></li>
  
  </ul>

app/views/shared/_restaurant_list.html.erb
    <!-- restaurants list，有多寫restaurant-item的class style -->
    <% @restaurants.each do |restaurant| %>
      <div class="col-sm-6 col-md-4">
        <div class="restaurant-item">
          <%= image_tag restaurant.image, class: "img-responsive center-block" %>
          <div class="caption">
            <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
            <p class="label label-default"><%= restaurant.category.name %><p>
            <p><%= truncate(restaurant.description, length: 80) %></p>
            <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
          </div>
        </div>
      </div>
    <% end %>
      
    <div class="clearfix"></div>
    <!-- 有generate kaminari paginate bootstrap style -->
    <div class="text-center">
      <%= paginate @restaurants %>
    </div>
      